// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogwfciieeuitlupjityp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nd2ZjaWllZXVpdGx1cGppdHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzczNzksImV4cCI6MjA2MjYxMzM3OX0.3TlOs1LDKL8Jju0Oq-4q7jbd_twzb7BxP-gz78CrWyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);